repos:
  - repo: https://github.com/privateai/pai-pre-commit-hook.git
    rev: v1.1-beta
    hooks:
      - id: pii-check
        args: ["--url", "URL", "--env-file-path", ".env"]
        verbose: true
