repos:
  - repo: https://github.com/ketaki99/test-pre-commit
    rev: test.6
    hooks:
      - id: pii-check
        entry: pii_check
        args:
          [
            "--url",
            "https://api.private-ai.com/deid/v3/process_text",
            "--env-file-path",
            ".env",
          ]
        verbose: true
